const main = () => {
  try {
    codigo;
  } catch (error) {
    console.error(`Deu erro e Ã© este ${error}`);
  }
};
